auto: true

#markdown: rdiscount
highlighter: 'pygments'
#paginate: 8
permalink: /:title

title: le fabuleux destin d'Yann
url: http://camscofie.github.io
feed: /atom.xml
author_info: <a href="http://mukosame.github.io/">Mukosame</a>
