auto: true

#markdown: rdiscount
highlighter: 'pygments'
#paginate: 8
permalink: /:title

title: 成长，长成自己的样子
url: http://May90.github.io
feed: /atom.xml
author_info: <a href="http://May90.github.io/">May</a>
